### ISSUE TITLE
this.select is not a function

### ISSUE THREAD

**Issue by AribaaG** [SpoonX/aurelia-datatable#100]
When adding select property the following error is occuring: this.select is not a function. How can i use a custom select method?

**Comment by nvtin** [comment]
@DCAribaa I think your question is hard to understand what you mean.
Can you give more detail about your issue?
Example: Your expectation, an example about your code and the errors. So everybody can understand and give solution for you.
:)

**Comment by AribaaG** [comment]
@nvtin I want to use the select bindable to provide a callback function. 

Example Code:
`<datatable sortable
                           select="selected(row)"
                           loading-indicator="<center>Ritten ophalen...</center>"
                           limit.bind="filters.limit"
                           repository.bind="ridesRepository"
                           columns.bind="columns"
                           actions.bind="actions"></datatable>`

When clicking on a row the following error is occurring: 
Uncaught TypeError: this.select is not a function
    at DataTable.selected 

`if (this.select) {
        return this.select(row);
      }`

**Comment by RWOverdijk** [comment]
@DCAribaa Your question is basic aurelia stuff. You need to bind, call, or something similar. You're passing in a string.

- http://kabaehr.de/blog/Aurelia-components-function-binding-mit-.call/
- http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-elements/4

@nvtin Thanks for requesting more info 👍

**Comment by AribaaG** [comment]
@RWOverdijk When i bind, delegate or trigger and put a log in de callback function. It's does nothing.

**Comment by RWOverdijk** [comment]
@DCAribaa Then you're doing it wrong. It's a bindable that will be called on select. There's nothing else to it. If you provide a gist.run or small repo that reproduces the issue I might be able to help.
