### ISSUE TITLE
Still have problem with Go to page 1 on search

### ISSUE THREAD

**Issue by jmdavid** [SpoonX/aurelia-datatable#103]
Hi,
I still have a problem with that.
I have that binding:
<datatable page.bind='page' ...
<pager page.bind="page" ...
I have a label showing the page:
${pagination}
and a getter in my js file:
@computedFrom('page') get pagination() { return 'Showing page ${this.page} of ${this.pages}.'; }
It works when I change page from the pager but not when doing a search. Refresh occurs but page remain as-is. (ex. I am in page 2 and do a search, page is still 2 after refresh)

Same behavior on online Swan example (I created lot of todos for having more than 30 in order to show the pager).

Thanks.

**Comment by jmdavid** [comment]
same behavior on online Swan example (I created lot of todos for having more than 30 in order to show the pager).

**Comment by RWOverdijk** [comment]
@jeremyvergnas Could you confirm/deny this?

**Comment by VMBindraban** [comment]
Confirmed.
