### ISSUE TITLE
Go to page 1 when searching

### ISSUE THREAD

**Issue by jeremyvergnas** [SpoonX/aurelia-datatable#50]
When we start a search with the `searchable` element, we should go back to page 1

**Comment by codezion** [comment]
The bug is still there. The list goes empty if later page selected before search.

**Comment by jeremyvergnas** [comment]
@VMBindraban

**Comment by VMBindraban** [comment]
@doktordirk Can you re-open this?

**Comment by RWOverdijk** [comment]
Published in 0.8.2

**Comment by jmdavid** [comment]
Hi,
I still have a problem with that.
I have that binding:
`<datatable page.bind='page' ...`
`<pager page.bind="page" ...`
I have a label showing the page:
`${pagination}`
and a getter in my js file:
`@computedFrom('page')
get pagination() {
    return 'Showing page ${this.page} of ${this.pages}.';
}`
It works when I change page from the pager but not when doing a search.  Refresh occurs but page remain as-is.  (ex. I am in page 2 and do a search, page is still 2 after refresh)

Thanks.
