### ISSUE TITLE
Demo page?

### ISSUE THREAD

**Issue by maroy1986** [SpoonX/aurelia-datatable#56]
I think you should put up a demo page online showing the possibilities your component has to offer so people can quickly decide if it's what they're looking for or not without having to checkout and build the whole thing.

Thanks!

**Comment by doktordirk** [comment]
there's some demo http://swan-example.spoonx.org

Username: example Password: example

**Comment by maroy1986** [comment]
Thanks for pointing out. Why not making it public so everyone could see it then?

**Comment by doktordirk** [comment]
it is (somewhere :smile: , swan sample client, i think) public. but of course you're right. hence, i left the issue open, so it'll be added here

**Comment by radenkozec** [comment]
We need better demos

**Comment by doktordirk** [comment]
yes

**Comment by RWOverdijk** [comment]
I'll take care of this soon. As soon as I'm done with the setup it'll be easier to add and / or update examples. Login credentials will be visible on the login page to make it easier.

**Comment by matdar** [comment]
Would you be able to publish the source for the demo page to git?
It would be helpful as the documentation for this plugin is a bit light.

**Comment by doktordirk** [comment]
@matdar https://github.com/SpoonX/swan-example-client
specifically 
https://github.com/SpoonX/swan-example-client/tree/master/src/scripts/page/datatable

**Comment by codezion** [comment]
Need a demo/example how to use row selection. The only way I got it working, do not work aurelia way. I.e. no access to data inside the class, so can not use the selection information, only log it. Is this the right way:
`<datatable
    ...
    select.bind="myclickCallback_method_in_model_class"
  ></datatable>`

**Comment by codezion** [comment]
I don't know why it didn't work 4 days ago, but now it does and right answer is select.call="mySelectMethod($event)"
