### ISSUE TITLE
lazy loading problem when running in gunicorn? maybe a configuration issue

### ISSUE THREAD

**Issue by guidorice** [SpoonX/aurelia-datatable#57]
Hi all, thanks for writing this very cool looking aurelia package. 

I am trying to use aurelia-datatable for the first time, but running into some module loading issues. 

I am using aurelia-cli 0.19.0 and my api environment is flask with gunicorn.

I managed to get all the dependencies installed and configured OK- because if I run the client with `au run` then the javascript loads without errors. So, no errors on: http://localhost:9000

However, when I load the app from gunicorn on http://localost:8888, then the javascript fails out at the aurelia-orm and aurelia-datatable steps. It's like there is some lazy module loading going on, and it is getting the script path wrong. I made a screenshot of my chrome dev tools so you can see the missing files and the exception.

The weird thing is, this same client code loads fine when running from the `au run` server. Also none of the other aurelia code has trouble loading from gunicorn.

Is there any way to configure it to not do lazy loading, and so it just gets put in vendor-bundle with everything else? I will append dependencies from aurelia.json as well if that helps.

```
          {
            "name": "homefront",
            "path": "../node_modules/homefront/dist",
            "main": "index"
          },
          "extend",
          "aurelia-api",
          "aurelia-view-manager",
          "get-prop",
          "typer",
          {
           "name": "aurelia-pager",
           "path": "../node_modules/aurelia-pager/dist/amd",
           "main": "aurelia-pager",
           "resources": [
             "bootstrap/pager.html"
           ]
         },         
        {
          "name": "aurelia-orm",
          "path": "../node_modules/aurelia-orm/dist/amd",
          "main": "aurelia-orm",
          "resources": [
            "component/association-select.html",
            "component/paged.html"
          ]
        },
        {
          "name": "aurelia-validation",
          "path": "../node_modules/aurelia-validation/dist/amd",
          "main": "index"
        },
          {
            "name": "aurelia-datatable",
            "path": "../node_modules/aurelia-datatable/dist/amd",
            "main": "aurelia-datatable",
            "resources": [
              "bootstrap/datatable.html"
            ]
          }
```

![aurelia-datatable](https://cloud.githubusercontent.com/assets/766758/18592138/c12060a8-7bf2-11e6-82e0-03ad2b57e847.png)

**Comment by guidorice** [comment]
I forgot to mention- running in gunicorn is necessary because the api is implemented in python.

**Comment by doktordirk** [comment]
"resources": [
            "component/association-select.html",
            "component/paged.html"
          ]
needs to be
          "resources": [
            "component/association-select",
            "component/paged"
          ]
forgot to fix the instructions there. but the datatable should be fine like this!?

**Comment by guidorice** [comment]
Hi doktor, thanks for the suggestion. I tried that change, but the aurelia-cli builder does not like that- not sure why

```
$ au run --watch
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/agr/Desktop/plateparty/client/node_modules/aurelia-orm/dist/amd/component/association-select
    at Glob.<anonymous> (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/index.js:39:11)
    at Glob.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/agr/Desktop/plateparty/client/node_modules/glob-stream/node_modules/glob/glob.js:728:12)

$ ls node_modules/aurelia-orm/dist/amd/component/*
node_modules/aurelia-orm/dist/amd/component/association-select.html
node_modules/aurelia-orm/dist/amd/component/association-select.js
node_modules/aurelia-orm/dist/amd/component/paged.html
node_modules/aurelia-orm/dist/amd/component/paged.js
```

**Comment by doktordirk** [comment]
ups, that crossed. i recheck my test project, and i have there  for all our resources a '.*' extension. so that's be for orm and datatable and pager i think

sample

``` js
          {
            "name": "aurelia-pager",
            "path": "../node_modules/aurelia-pager/dist/amd",
            "main": "aurelia-pager",
            "resources": [
              "bootstrap/pager.*"
            ]
          },
          {
            "name": "homefront",
            "path": "../node_modules/homefront/dist",
            "main": "index"
          },
          {
            "name": "aurelia-datatable",
            "path": "../node_modules/aurelia-datatable/dist/amd",
            "main": "aurelia-datatable",
            "resources": [
              "bootstrap/datatable.*"
            ]
          },
          {
          "name": "aurelia-orm",
          "path": "../node_modules/aurelia-orm/dist/amd",
          "main": "aurelia-orm",
          "resources": [
            "component/association-select.*",
            "component/paged.*"
          ]},
```

**Comment by doktordirk** [comment]
argh, not my day. just add everything  it complains about after the dist/amd/ to the corresponding resources sections.

**Comment by guidorice** [comment]
OK so I have changed it to:

```
{
          "name": "aurelia-orm",
          "path": "../node_modules/aurelia-orm/dist/amd",
          "main": "aurelia-orm",
          "resources": [
            "component/association-select.html",
            "component/association-select.js",
            "component/paged.html",
            "component/paged.js"
          ]
 }
```

but now I get an exception about define()

> vendor-bundle.js:4197 Uncaught Error: Mismatched anonymous define() module: function (exports, _aureliaOrm, _getProp, _aureliaDependencyInjection, _aureliaBinding, _aureliaTemplating) {
>   'use strict';

**Comment by doktordirk** [comment]
hmm. i think i know what that was (i mean the whole issue). basically it was no js files in resources, but dummy import them all. i had that prepared, but run into issues with jspm then, so i didn't follow up. 

so, either remove all resources *.js and try to dummy import all those in eg main.js, or go back to your first version (which had no js as well i think), and copy/symlink the whole /node_modules folder into the dist folder resp the folder you serve from, or wait until i've figured it out.
