### ISSUE TITLE
Reload datatable after edit or destroy action

### ISSUE THREAD

**Issue by jimisens** [SpoonX/aurelia-datatable#68]
Hi Everybody, 
I'm working with the datatable plugin with success but I cannot found a way to manually-reload the datatable content. 
Is there any way for do it in a function ? After Edit or Delete function ? 
I need this if the content is changed server side. 

Thanks

**Comment by RWOverdijk** [comment]
@jimisens You can reload it by calling [.reload()](https://github.com/SpoonX/aurelia-datatable/blob/master/src/datatable.js#L211) on the datatable. You can get a ref to it to get access to that method :)

``` html
<datatable view-model.ref="datatable"></datatable>
```

``` js
class MyViewModel {
  someMethod() {
    this.datatable.reload();
  }
}
```

**Comment by jimisens** [comment]
Ok it works! Thank you @RWOverdijk
