### ISSUE TITLE
Production bundle : TypeError: e is undefined in Firefox

### ISSUE THREAD

**Issue by jimisens** [SpoonX/aurelia-datatable#71]
Hello Everybody!!
I'm actually having an error in Firefox, and the datatable doesn't load the content even if the content is coming from the server (network tab in firefox)
I use AURELIA CLI for create a production bundle : au build --env prod 
and the compiled bundle is now in the server.
This error happen in firefox in production mode

![captura de pantalla 2016-12-16 a la s 12 11 08](https://cloud.githubusercontent.com/assets/8067544/21273451/46074470-c389-11e6-9323-3ad46a6d04f2.png)

Somebody can help me please ?

**Comment by RWOverdijk** [comment]
@jeremyvergnas And this one, too.

**Comment by RWOverdijk** [comment]
@jimisens We just released a patch. Could you test it? It appears to work here.
