### ISSUE TITLE
Weird actions

### ISSUE THREAD

**Issue by natrim** [SpoonX/aurelia-datatable#96]
In documentation it says to use
`  destroy.delegate="myEventCallback($event)"
      edit.delegate="myEditImplementation($event)"`

but they are not events but bindable

you can only use
` destroy.call="myEventCallback($event)"
      edit.call="myEditImplementation($event)"`

but then you don't have the second argument (index)

**Comment by RWOverdijk** [comment]
@natrim That looks like an issue in the docs, I'm sorry about that. Perhaps what you're looking for is the method of defining actions (giving you more control). If you want the event, it has to be implemented (should be simple enough). Want to give it a go?

**Comment by nvtin** [comment]
Haha. I have got the same issue. So I have tried use `edit.call()` and `destroy.call()` function for edit, destroy instead of `...delegate()` as displayed in documentation. And I worked well. So please update it. Thanks.

**Comment by RWOverdijk** [comment]
@nvtin The docs are in the docs directory, feel free to PR

**Comment by nvtin** [comment]
@RWOverdijk I have just made a pull request for update document. Please check and approve it
https://github.com/SpoonX/aurelia-datatable/pull/99

**Comment by RWOverdijk** [comment]
Docs updated!
