### ISSUE TITLE
Action buttons not showing up for edit and destroy

### ISSUE THREAD

**Issue by jasontll** [SpoonX/aurelia-datatable#98]
When using edit.delegate and destroy.delegate the button will not show up. As a workaround I have to do edit.bind instead, is that a normal behavior? I need to wrap the bound method to another method to have them work, Which is weird.

**Comment by nvtin** [comment]
@jasontll Yes That is old document.
so please check this issue to get more detail https://github.com/SpoonX/aurelia-datatable/issues/96

**Comment by RWOverdijk** [comment]
Docs updated!
